### ISSUE TITLE
gh

### ISSUE THREAD

**Issue by Derpitron** [Vishard-006/ReqDank#1]
# gh
![image](https://user-images.githubusercontent.com/46134462/132983652-922ef3e7-6afb-43b3-be31-30a3370fb4f0.png)
gh

also make the repo private bro

**Comment by Vishard-006** [comment]
1. Doesnt matter what your branch is named mate
2. Encourage,Foster,Support and promote the open source ideals which furthered the development of software to its present state so kill yourself

**Comment by Derpitron** [comment]
this is a public forum, what's with the language
